#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None



class sai_thrift_fdb_entry_t:
  """
  Attributes:
   - mac_address
   - bv_id
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'mac_address', None, None, ), # 1
    (2, TType.I64, 'bv_id', None, None, ), # 2
  )

  def __init__(self, mac_address=None, bv_id=None,):
    self.mac_address = mac_address
    self.bv_id = bv_id

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.mac_address = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I64:
          self.bv_id = iprot.readI64();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_fdb_entry_t')
    if self.mac_address is not None:
      oprot.writeFieldBegin('mac_address', TType.STRING, 1)
      oprot.writeString(self.mac_address)
      oprot.writeFieldEnd()
    if self.bv_id is not None:
      oprot.writeFieldBegin('bv_id', TType.I64, 2)
      oprot.writeI64(self.bv_id)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.mac_address)
    value = (value * 31) ^ hash(self.bv_id)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_vlan_port_t:
  """
  Attributes:
   - port_id
   - tagging_mode
  """

  thrift_spec = (
    None, # 0
    (1, TType.I64, 'port_id', None, None, ), # 1
    (2, TType.BYTE, 'tagging_mode', None, None, ), # 2
  )

  def __init__(self, port_id=None, tagging_mode=None,):
    self.port_id = port_id
    self.tagging_mode = tagging_mode

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I64:
          self.port_id = iprot.readI64();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.BYTE:
          self.tagging_mode = iprot.readByte();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_vlan_port_t')
    if self.port_id is not None:
      oprot.writeFieldBegin('port_id', TType.I64, 1)
      oprot.writeI64(self.port_id)
      oprot.writeFieldEnd()
    if self.tagging_mode is not None:
      oprot.writeFieldBegin('tagging_mode', TType.BYTE, 2)
      oprot.writeByte(self.tagging_mode)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.port_id)
    value = (value * 31) ^ hash(self.tagging_mode)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_ip_t:
  """
  Attributes:
   - ip4
   - ip6
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'ip4', None, None, ), # 1
    (2, TType.STRING, 'ip6', None, None, ), # 2
  )

  def __init__(self, ip4=None, ip6=None,):
    self.ip4 = ip4
    self.ip6 = ip6

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.ip4 = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.ip6 = iprot.readString();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_ip_t')
    if self.ip4 is not None:
      oprot.writeFieldBegin('ip4', TType.STRING, 1)
      oprot.writeString(self.ip4)
      oprot.writeFieldEnd()
    if self.ip6 is not None:
      oprot.writeFieldBegin('ip6', TType.STRING, 2)
      oprot.writeString(self.ip6)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.ip4)
    value = (value * 31) ^ hash(self.ip6)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_ip_address_t:
  """
  Attributes:
   - addr_family
   - addr
  """

  thrift_spec = (
    None, # 0
    (1, TType.BYTE, 'addr_family', None, None, ), # 1
    (2, TType.STRUCT, 'addr', (sai_thrift_ip_t, sai_thrift_ip_t.thrift_spec), None, ), # 2
  )

  def __init__(self, addr_family=None, addr=None,):
    self.addr_family = addr_family
    self.addr = addr

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.BYTE:
          self.addr_family = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRUCT:
          self.addr = sai_thrift_ip_t()
          self.addr.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_ip_address_t')
    if self.addr_family is not None:
      oprot.writeFieldBegin('addr_family', TType.BYTE, 1)
      oprot.writeByte(self.addr_family)
      oprot.writeFieldEnd()
    if self.addr is not None:
      oprot.writeFieldBegin('addr', TType.STRUCT, 2)
      self.addr.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.addr_family)
    value = (value * 31) ^ hash(self.addr)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_ip_prefix_t:
  """
  Attributes:
   - addr_family
   - addr
   - mask
  """

  thrift_spec = (
    None, # 0
    (1, TType.BYTE, 'addr_family', None, None, ), # 1
    (2, TType.STRUCT, 'addr', (sai_thrift_ip_t, sai_thrift_ip_t.thrift_spec), None, ), # 2
    (3, TType.STRUCT, 'mask', (sai_thrift_ip_t, sai_thrift_ip_t.thrift_spec), None, ), # 3
  )

  def __init__(self, addr_family=None, addr=None, mask=None,):
    self.addr_family = addr_family
    self.addr = addr
    self.mask = mask

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.BYTE:
          self.addr_family = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRUCT:
          self.addr = sai_thrift_ip_t()
          self.addr.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRUCT:
          self.mask = sai_thrift_ip_t()
          self.mask.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_ip_prefix_t')
    if self.addr_family is not None:
      oprot.writeFieldBegin('addr_family', TType.BYTE, 1)
      oprot.writeByte(self.addr_family)
      oprot.writeFieldEnd()
    if self.addr is not None:
      oprot.writeFieldBegin('addr', TType.STRUCT, 2)
      self.addr.write(oprot)
      oprot.writeFieldEnd()
    if self.mask is not None:
      oprot.writeFieldBegin('mask', TType.STRUCT, 3)
      self.mask.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.addr_family)
    value = (value * 31) ^ hash(self.addr)
    value = (value * 31) ^ hash(self.mask)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_object_list_t:
  """
  Attributes:
   - count
   - object_id_list
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'count', None, None, ), # 1
    (2, TType.LIST, 'object_id_list', (TType.I64,None), None, ), # 2
  )

  def __init__(self, count=None, object_id_list=None,):
    self.count = count
    self.object_id_list = object_id_list

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.count = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.LIST:
          self.object_id_list = []
          (_etype3, _size0) = iprot.readListBegin()
          for _i4 in xrange(_size0):
            _elem5 = iprot.readI64();
            self.object_id_list.append(_elem5)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_object_list_t')
    if self.count is not None:
      oprot.writeFieldBegin('count', TType.I32, 1)
      oprot.writeI32(self.count)
      oprot.writeFieldEnd()
    if self.object_id_list is not None:
      oprot.writeFieldBegin('object_id_list', TType.LIST, 2)
      oprot.writeListBegin(TType.I64, len(self.object_id_list))
      for iter6 in self.object_id_list:
        oprot.writeI64(iter6)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.count)
    value = (value * 31) ^ hash(self.object_id_list)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_vlan_list_t:
  """
  Attributes:
   - vlan_count
   - vlan_list
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'vlan_count', None, None, ), # 1
    (2, TType.LIST, 'vlan_list', (TType.I16,None), None, ), # 2
  )

  def __init__(self, vlan_count=None, vlan_list=None,):
    self.vlan_count = vlan_count
    self.vlan_list = vlan_list

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.vlan_count = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.LIST:
          self.vlan_list = []
          (_etype10, _size7) = iprot.readListBegin()
          for _i11 in xrange(_size7):
            _elem12 = iprot.readI16();
            self.vlan_list.append(_elem12)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_vlan_list_t')
    if self.vlan_count is not None:
      oprot.writeFieldBegin('vlan_count', TType.I32, 1)
      oprot.writeI32(self.vlan_count)
      oprot.writeFieldEnd()
    if self.vlan_list is not None:
      oprot.writeFieldBegin('vlan_list', TType.LIST, 2)
      oprot.writeListBegin(TType.I16, len(self.vlan_list))
      for iter13 in self.vlan_list:
        oprot.writeI16(iter13)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.vlan_count)
    value = (value * 31) ^ hash(self.vlan_list)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_s32_list_t:
  """
  Attributes:
   - count
   - s32list
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'count', None, None, ), # 1
    (2, TType.LIST, 's32list', (TType.I32,None), None, ), # 2
  )

  def __init__(self, count=None, s32list=None,):
    self.count = count
    self.s32list = s32list

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.count = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.LIST:
          self.s32list = []
          (_etype17, _size14) = iprot.readListBegin()
          for _i18 in xrange(_size14):
            _elem19 = iprot.readI32();
            self.s32list.append(_elem19)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_s32_list_t')
    if self.count is not None:
      oprot.writeFieldBegin('count', TType.I32, 1)
      oprot.writeI32(self.count)
      oprot.writeFieldEnd()
    if self.s32list is not None:
      oprot.writeFieldBegin('s32list', TType.LIST, 2)
      oprot.writeListBegin(TType.I32, len(self.s32list))
      for iter20 in self.s32list:
        oprot.writeI32(iter20)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.count)
    value = (value * 31) ^ hash(self.s32list)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_acl_mask_t:
  """
  Attributes:
   - u8
   - s8
   - u16
   - s16
   - u32
   - s32
   - mac
   - ip4
   - ip6
  """

  thrift_spec = (
    None, # 0
    (1, TType.BYTE, 'u8', None, None, ), # 1
    (2, TType.BYTE, 's8', None, None, ), # 2
    (3, TType.I16, 'u16', None, None, ), # 3
    (4, TType.I16, 's16', None, None, ), # 4
    (5, TType.I32, 'u32', None, None, ), # 5
    (6, TType.I32, 's32', None, None, ), # 6
    (7, TType.STRING, 'mac', None, None, ), # 7
    (8, TType.STRING, 'ip4', None, None, ), # 8
    (9, TType.STRING, 'ip6', None, None, ), # 9
  )

  def __init__(self, u8=None, s8=None, u16=None, s16=None, u32=None, s32=None, mac=None, ip4=None, ip6=None,):
    self.u8 = u8
    self.s8 = s8
    self.u16 = u16
    self.s16 = s16
    self.u32 = u32
    self.s32 = s32
    self.mac = mac
    self.ip4 = ip4
    self.ip6 = ip6

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.BYTE:
          self.u8 = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.BYTE:
          self.s8 = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I16:
          self.u16 = iprot.readI16();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.I16:
          self.s16 = iprot.readI16();
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.I32:
          self.u32 = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.I32:
          self.s32 = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.STRING:
          self.mac = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 8:
        if ftype == TType.STRING:
          self.ip4 = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 9:
        if ftype == TType.STRING:
          self.ip6 = iprot.readString();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_acl_mask_t')
    if self.u8 is not None:
      oprot.writeFieldBegin('u8', TType.BYTE, 1)
      oprot.writeByte(self.u8)
      oprot.writeFieldEnd()
    if self.s8 is not None:
      oprot.writeFieldBegin('s8', TType.BYTE, 2)
      oprot.writeByte(self.s8)
      oprot.writeFieldEnd()
    if self.u16 is not None:
      oprot.writeFieldBegin('u16', TType.I16, 3)
      oprot.writeI16(self.u16)
      oprot.writeFieldEnd()
    if self.s16 is not None:
      oprot.writeFieldBegin('s16', TType.I16, 4)
      oprot.writeI16(self.s16)
      oprot.writeFieldEnd()
    if self.u32 is not None:
      oprot.writeFieldBegin('u32', TType.I32, 5)
      oprot.writeI32(self.u32)
      oprot.writeFieldEnd()
    if self.s32 is not None:
      oprot.writeFieldBegin('s32', TType.I32, 6)
      oprot.writeI32(self.s32)
      oprot.writeFieldEnd()
    if self.mac is not None:
      oprot.writeFieldBegin('mac', TType.STRING, 7)
      oprot.writeString(self.mac)
      oprot.writeFieldEnd()
    if self.ip4 is not None:
      oprot.writeFieldBegin('ip4', TType.STRING, 8)
      oprot.writeString(self.ip4)
      oprot.writeFieldEnd()
    if self.ip6 is not None:
      oprot.writeFieldBegin('ip6', TType.STRING, 9)
      oprot.writeString(self.ip6)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.u8)
    value = (value * 31) ^ hash(self.s8)
    value = (value * 31) ^ hash(self.u16)
    value = (value * 31) ^ hash(self.s16)
    value = (value * 31) ^ hash(self.u32)
    value = (value * 31) ^ hash(self.s32)
    value = (value * 31) ^ hash(self.mac)
    value = (value * 31) ^ hash(self.ip4)
    value = (value * 31) ^ hash(self.ip6)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_acl_data_t:
  """
  Attributes:
   - u8
   - s8
   - u16
   - s16
   - u32
   - s32
   - mac
   - ip4
   - ip6
   - oid
   - objlist
  """

  thrift_spec = (
    None, # 0
    (1, TType.BYTE, 'u8', None, None, ), # 1
    (2, TType.BYTE, 's8', None, None, ), # 2
    (3, TType.I16, 'u16', None, None, ), # 3
    (4, TType.I16, 's16', None, None, ), # 4
    (5, TType.I32, 'u32', None, None, ), # 5
    (6, TType.I32, 's32', None, None, ), # 6
    (7, TType.STRING, 'mac', None, None, ), # 7
    (8, TType.STRING, 'ip4', None, None, ), # 8
    (9, TType.STRING, 'ip6', None, None, ), # 9
    (10, TType.I64, 'oid', None, None, ), # 10
    (11, TType.STRUCT, 'objlist', (sai_thrift_object_list_t, sai_thrift_object_list_t.thrift_spec), None, ), # 11
  )

  def __init__(self, u8=None, s8=None, u16=None, s16=None, u32=None, s32=None, mac=None, ip4=None, ip6=None, oid=None, objlist=None,):
    self.u8 = u8
    self.s8 = s8
    self.u16 = u16
    self.s16 = s16
    self.u32 = u32
    self.s32 = s32
    self.mac = mac
    self.ip4 = ip4
    self.ip6 = ip6
    self.oid = oid
    self.objlist = objlist

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.BYTE:
          self.u8 = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.BYTE:
          self.s8 = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I16:
          self.u16 = iprot.readI16();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.I16:
          self.s16 = iprot.readI16();
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.I32:
          self.u32 = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.I32:
          self.s32 = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.STRING:
          self.mac = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 8:
        if ftype == TType.STRING:
          self.ip4 = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 9:
        if ftype == TType.STRING:
          self.ip6 = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 10:
        if ftype == TType.I64:
          self.oid = iprot.readI64();
        else:
          iprot.skip(ftype)
      elif fid == 11:
        if ftype == TType.STRUCT:
          self.objlist = sai_thrift_object_list_t()
          self.objlist.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_acl_data_t')
    if self.u8 is not None:
      oprot.writeFieldBegin('u8', TType.BYTE, 1)
      oprot.writeByte(self.u8)
      oprot.writeFieldEnd()
    if self.s8 is not None:
      oprot.writeFieldBegin('s8', TType.BYTE, 2)
      oprot.writeByte(self.s8)
      oprot.writeFieldEnd()
    if self.u16 is not None:
      oprot.writeFieldBegin('u16', TType.I16, 3)
      oprot.writeI16(self.u16)
      oprot.writeFieldEnd()
    if self.s16 is not None:
      oprot.writeFieldBegin('s16', TType.I16, 4)
      oprot.writeI16(self.s16)
      oprot.writeFieldEnd()
    if self.u32 is not None:
      oprot.writeFieldBegin('u32', TType.I32, 5)
      oprot.writeI32(self.u32)
      oprot.writeFieldEnd()
    if self.s32 is not None:
      oprot.writeFieldBegin('s32', TType.I32, 6)
      oprot.writeI32(self.s32)
      oprot.writeFieldEnd()
    if self.mac is not None:
      oprot.writeFieldBegin('mac', TType.STRING, 7)
      oprot.writeString(self.mac)
      oprot.writeFieldEnd()
    if self.ip4 is not None:
      oprot.writeFieldBegin('ip4', TType.STRING, 8)
      oprot.writeString(self.ip4)
      oprot.writeFieldEnd()
    if self.ip6 is not None:
      oprot.writeFieldBegin('ip6', TType.STRING, 9)
      oprot.writeString(self.ip6)
      oprot.writeFieldEnd()
    if self.oid is not None:
      oprot.writeFieldBegin('oid', TType.I64, 10)
      oprot.writeI64(self.oid)
      oprot.writeFieldEnd()
    if self.objlist is not None:
      oprot.writeFieldBegin('objlist', TType.STRUCT, 11)
      self.objlist.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.u8)
    value = (value * 31) ^ hash(self.s8)
    value = (value * 31) ^ hash(self.u16)
    value = (value * 31) ^ hash(self.s16)
    value = (value * 31) ^ hash(self.u32)
    value = (value * 31) ^ hash(self.s32)
    value = (value * 31) ^ hash(self.mac)
    value = (value * 31) ^ hash(self.ip4)
    value = (value * 31) ^ hash(self.ip6)
    value = (value * 31) ^ hash(self.oid)
    value = (value * 31) ^ hash(self.objlist)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_acl_field_data_t:
  """
  Attributes:
   - enable
   - mask
   - data
  """

  thrift_spec = (
    None, # 0
    (1, TType.BOOL, 'enable', None, None, ), # 1
    (2, TType.STRUCT, 'mask', (sai_thrift_acl_mask_t, sai_thrift_acl_mask_t.thrift_spec), None, ), # 2
    (3, TType.STRUCT, 'data', (sai_thrift_acl_data_t, sai_thrift_acl_data_t.thrift_spec), None, ), # 3
  )

  def __init__(self, enable=None, mask=None, data=None,):
    self.enable = enable
    self.mask = mask
    self.data = data

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.BOOL:
          self.enable = iprot.readBool();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRUCT:
          self.mask = sai_thrift_acl_mask_t()
          self.mask.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRUCT:
          self.data = sai_thrift_acl_data_t()
          self.data.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_acl_field_data_t')
    if self.enable is not None:
      oprot.writeFieldBegin('enable', TType.BOOL, 1)
      oprot.writeBool(self.enable)
      oprot.writeFieldEnd()
    if self.mask is not None:
      oprot.writeFieldBegin('mask', TType.STRUCT, 2)
      self.mask.write(oprot)
      oprot.writeFieldEnd()
    if self.data is not None:
      oprot.writeFieldBegin('data', TType.STRUCT, 3)
      self.data.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.enable)
    value = (value * 31) ^ hash(self.mask)
    value = (value * 31) ^ hash(self.data)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_acl_parameter_t:
  """
  Attributes:
   - u8
   - s8
   - u16
   - s16
   - u32
   - s32
   - mac
   - ip4
   - ip6
   - oid
   - objlist
  """

  thrift_spec = (
    None, # 0
    (1, TType.BYTE, 'u8', None, None, ), # 1
    (2, TType.BYTE, 's8', None, None, ), # 2
    (3, TType.I16, 'u16', None, None, ), # 3
    (4, TType.I16, 's16', None, None, ), # 4
    (5, TType.I32, 'u32', None, None, ), # 5
    (6, TType.I32, 's32', None, None, ), # 6
    (7, TType.STRING, 'mac', None, None, ), # 7
    (8, TType.STRING, 'ip4', None, None, ), # 8
    (9, TType.STRING, 'ip6', None, None, ), # 9
    (10, TType.I64, 'oid', None, None, ), # 10
    (11, TType.STRUCT, 'objlist', (sai_thrift_object_list_t, sai_thrift_object_list_t.thrift_spec), None, ), # 11
  )

  def __init__(self, u8=None, s8=None, u16=None, s16=None, u32=None, s32=None, mac=None, ip4=None, ip6=None, oid=None, objlist=None,):
    self.u8 = u8
    self.s8 = s8
    self.u16 = u16
    self.s16 = s16
    self.u32 = u32
    self.s32 = s32
    self.mac = mac
    self.ip4 = ip4
    self.ip6 = ip6
    self.oid = oid
    self.objlist = objlist

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.BYTE:
          self.u8 = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.BYTE:
          self.s8 = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I16:
          self.u16 = iprot.readI16();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.I16:
          self.s16 = iprot.readI16();
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.I32:
          self.u32 = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.I32:
          self.s32 = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.STRING:
          self.mac = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 8:
        if ftype == TType.STRING:
          self.ip4 = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 9:
        if ftype == TType.STRING:
          self.ip6 = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 10:
        if ftype == TType.I64:
          self.oid = iprot.readI64();
        else:
          iprot.skip(ftype)
      elif fid == 11:
        if ftype == TType.STRUCT:
          self.objlist = sai_thrift_object_list_t()
          self.objlist.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_acl_parameter_t')
    if self.u8 is not None:
      oprot.writeFieldBegin('u8', TType.BYTE, 1)
      oprot.writeByte(self.u8)
      oprot.writeFieldEnd()
    if self.s8 is not None:
      oprot.writeFieldBegin('s8', TType.BYTE, 2)
      oprot.writeByte(self.s8)
      oprot.writeFieldEnd()
    if self.u16 is not None:
      oprot.writeFieldBegin('u16', TType.I16, 3)
      oprot.writeI16(self.u16)
      oprot.writeFieldEnd()
    if self.s16 is not None:
      oprot.writeFieldBegin('s16', TType.I16, 4)
      oprot.writeI16(self.s16)
      oprot.writeFieldEnd()
    if self.u32 is not None:
      oprot.writeFieldBegin('u32', TType.I32, 5)
      oprot.writeI32(self.u32)
      oprot.writeFieldEnd()
    if self.s32 is not None:
      oprot.writeFieldBegin('s32', TType.I32, 6)
      oprot.writeI32(self.s32)
      oprot.writeFieldEnd()
    if self.mac is not None:
      oprot.writeFieldBegin('mac', TType.STRING, 7)
      oprot.writeString(self.mac)
      oprot.writeFieldEnd()
    if self.ip4 is not None:
      oprot.writeFieldBegin('ip4', TType.STRING, 8)
      oprot.writeString(self.ip4)
      oprot.writeFieldEnd()
    if self.ip6 is not None:
      oprot.writeFieldBegin('ip6', TType.STRING, 9)
      oprot.writeString(self.ip6)
      oprot.writeFieldEnd()
    if self.oid is not None:
      oprot.writeFieldBegin('oid', TType.I64, 10)
      oprot.writeI64(self.oid)
      oprot.writeFieldEnd()
    if self.objlist is not None:
      oprot.writeFieldBegin('objlist', TType.STRUCT, 11)
      self.objlist.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.u8)
    value = (value * 31) ^ hash(self.s8)
    value = (value * 31) ^ hash(self.u16)
    value = (value * 31) ^ hash(self.s16)
    value = (value * 31) ^ hash(self.u32)
    value = (value * 31) ^ hash(self.s32)
    value = (value * 31) ^ hash(self.mac)
    value = (value * 31) ^ hash(self.ip4)
    value = (value * 31) ^ hash(self.ip6)
    value = (value * 31) ^ hash(self.oid)
    value = (value * 31) ^ hash(self.objlist)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_acl_action_data_t:
  """
  Attributes:
   - enable
   - parameter
  """

  thrift_spec = (
    None, # 0
    (1, TType.BOOL, 'enable', None, None, ), # 1
    (2, TType.STRUCT, 'parameter', (sai_thrift_acl_parameter_t, sai_thrift_acl_parameter_t.thrift_spec), None, ), # 2
  )

  def __init__(self, enable=None, parameter=None,):
    self.enable = enable
    self.parameter = parameter

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.BOOL:
          self.enable = iprot.readBool();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRUCT:
          self.parameter = sai_thrift_acl_parameter_t()
          self.parameter.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_acl_action_data_t')
    if self.enable is not None:
      oprot.writeFieldBegin('enable', TType.BOOL, 1)
      oprot.writeBool(self.enable)
      oprot.writeFieldEnd()
    if self.parameter is not None:
      oprot.writeFieldBegin('parameter', TType.STRUCT, 2)
      self.parameter.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.enable)
    value = (value * 31) ^ hash(self.parameter)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_u8_list_t:
  """
  Attributes:
   - count
   - u8list
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'count', None, None, ), # 1
    (2, TType.LIST, 'u8list', (TType.BYTE,None), None, ), # 2
  )

  def __init__(self, count=None, u8list=None,):
    self.count = count
    self.u8list = u8list

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.count = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.LIST:
          self.u8list = []
          (_etype24, _size21) = iprot.readListBegin()
          for _i25 in xrange(_size21):
            _elem26 = iprot.readByte();
            self.u8list.append(_elem26)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_u8_list_t')
    if self.count is not None:
      oprot.writeFieldBegin('count', TType.I32, 1)
      oprot.writeI32(self.count)
      oprot.writeFieldEnd()
    if self.u8list is not None:
      oprot.writeFieldBegin('u8list', TType.LIST, 2)
      oprot.writeListBegin(TType.BYTE, len(self.u8list))
      for iter27 in self.u8list:
        oprot.writeByte(iter27)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.count)
    value = (value * 31) ^ hash(self.u8list)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_s8_list_t:
  """
  Attributes:
   - count
   - s8list
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'count', None, None, ), # 1
    (2, TType.LIST, 's8list', (TType.BYTE,None), None, ), # 2
  )

  def __init__(self, count=None, s8list=None,):
    self.count = count
    self.s8list = s8list

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.count = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.LIST:
          self.s8list = []
          (_etype31, _size28) = iprot.readListBegin()
          for _i32 in xrange(_size28):
            _elem33 = iprot.readByte();
            self.s8list.append(_elem33)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_s8_list_t')
    if self.count is not None:
      oprot.writeFieldBegin('count', TType.I32, 1)
      oprot.writeI32(self.count)
      oprot.writeFieldEnd()
    if self.s8list is not None:
      oprot.writeFieldBegin('s8list', TType.LIST, 2)
      oprot.writeListBegin(TType.BYTE, len(self.s8list))
      for iter34 in self.s8list:
        oprot.writeByte(iter34)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.count)
    value = (value * 31) ^ hash(self.s8list)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_u32_list_t:
  """
  Attributes:
   - count
   - u32list
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'count', None, None, ), # 1
    (2, TType.LIST, 'u32list', (TType.I32,None), None, ), # 2
  )

  def __init__(self, count=None, u32list=None,):
    self.count = count
    self.u32list = u32list

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.count = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.LIST:
          self.u32list = []
          (_etype38, _size35) = iprot.readListBegin()
          for _i39 in xrange(_size35):
            _elem40 = iprot.readI32();
            self.u32list.append(_elem40)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_u32_list_t')
    if self.count is not None:
      oprot.writeFieldBegin('count', TType.I32, 1)
      oprot.writeI32(self.count)
      oprot.writeFieldEnd()
    if self.u32list is not None:
      oprot.writeFieldBegin('u32list', TType.LIST, 2)
      oprot.writeListBegin(TType.I32, len(self.u32list))
      for iter41 in self.u32list:
        oprot.writeI32(iter41)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.count)
    value = (value * 31) ^ hash(self.u32list)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_qos_map_params_t:
  """
  Attributes:
   - tc
   - dscp
   - dot1p
   - prio
   - pg
   - queue_index
   - color
  """

  thrift_spec = (
    None, # 0
    (1, TType.BYTE, 'tc', None, None, ), # 1
    (2, TType.BYTE, 'dscp', None, None, ), # 2
    (3, TType.BYTE, 'dot1p', None, None, ), # 3
    (4, TType.BYTE, 'prio', None, None, ), # 4
    (5, TType.BYTE, 'pg', None, None, ), # 5
    (6, TType.BYTE, 'queue_index', None, None, ), # 6
    (7, TType.BYTE, 'color', None, None, ), # 7
  )

  def __init__(self, tc=None, dscp=None, dot1p=None, prio=None, pg=None, queue_index=None, color=None,):
    self.tc = tc
    self.dscp = dscp
    self.dot1p = dot1p
    self.prio = prio
    self.pg = pg
    self.queue_index = queue_index
    self.color = color

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.BYTE:
          self.tc = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.BYTE:
          self.dscp = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.BYTE:
          self.dot1p = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.BYTE:
          self.prio = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.BYTE:
          self.pg = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.BYTE:
          self.queue_index = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.BYTE:
          self.color = iprot.readByte();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_qos_map_params_t')
    if self.tc is not None:
      oprot.writeFieldBegin('tc', TType.BYTE, 1)
      oprot.writeByte(self.tc)
      oprot.writeFieldEnd()
    if self.dscp is not None:
      oprot.writeFieldBegin('dscp', TType.BYTE, 2)
      oprot.writeByte(self.dscp)
      oprot.writeFieldEnd()
    if self.dot1p is not None:
      oprot.writeFieldBegin('dot1p', TType.BYTE, 3)
      oprot.writeByte(self.dot1p)
      oprot.writeFieldEnd()
    if self.prio is not None:
      oprot.writeFieldBegin('prio', TType.BYTE, 4)
      oprot.writeByte(self.prio)
      oprot.writeFieldEnd()
    if self.pg is not None:
      oprot.writeFieldBegin('pg', TType.BYTE, 5)
      oprot.writeByte(self.pg)
      oprot.writeFieldEnd()
    if self.queue_index is not None:
      oprot.writeFieldBegin('queue_index', TType.BYTE, 6)
      oprot.writeByte(self.queue_index)
      oprot.writeFieldEnd()
    if self.color is not None:
      oprot.writeFieldBegin('color', TType.BYTE, 7)
      oprot.writeByte(self.color)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.tc)
    value = (value * 31) ^ hash(self.dscp)
    value = (value * 31) ^ hash(self.dot1p)
    value = (value * 31) ^ hash(self.prio)
    value = (value * 31) ^ hash(self.pg)
    value = (value * 31) ^ hash(self.queue_index)
    value = (value * 31) ^ hash(self.color)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_qos_map_t:
  """
  Attributes:
   - key
   - value
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRUCT, 'key', (sai_thrift_qos_map_params_t, sai_thrift_qos_map_params_t.thrift_spec), None, ), # 1
    (2, TType.STRUCT, 'value', (sai_thrift_qos_map_params_t, sai_thrift_qos_map_params_t.thrift_spec), None, ), # 2
  )

  def __init__(self, key=None, value=None,):
    self.key = key
    self.value = value

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRUCT:
          self.key = sai_thrift_qos_map_params_t()
          self.key.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRUCT:
          self.value = sai_thrift_qos_map_params_t()
          self.value.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_qos_map_t')
    if self.key is not None:
      oprot.writeFieldBegin('key', TType.STRUCT, 1)
      self.key.write(oprot)
      oprot.writeFieldEnd()
    if self.value is not None:
      oprot.writeFieldBegin('value', TType.STRUCT, 2)
      self.value.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.key)
    value = (value * 31) ^ hash(self.value)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_qos_map_list_t:
  """
  Attributes:
   - count
   - map_list
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'count', None, None, ), # 1
    (2, TType.LIST, 'map_list', (TType.STRUCT,(sai_thrift_qos_map_t, sai_thrift_qos_map_t.thrift_spec)), None, ), # 2
  )

  def __init__(self, count=None, map_list=None,):
    self.count = count
    self.map_list = map_list

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.count = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.LIST:
          self.map_list = []
          (_etype45, _size42) = iprot.readListBegin()
          for _i46 in xrange(_size42):
            _elem47 = sai_thrift_qos_map_t()
            _elem47.read(iprot)
            self.map_list.append(_elem47)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_qos_map_list_t')
    if self.count is not None:
      oprot.writeFieldBegin('count', TType.I32, 1)
      oprot.writeI32(self.count)
      oprot.writeFieldEnd()
    if self.map_list is not None:
      oprot.writeFieldBegin('map_list', TType.LIST, 2)
      oprot.writeListBegin(TType.STRUCT, len(self.map_list))
      for iter48 in self.map_list:
        iter48.write(oprot)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.count)
    value = (value * 31) ^ hash(self.map_list)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_attribute_value_t:
  """
  Attributes:
   - booldata
   - chardata
   - u8
   - s8
   - u16
   - s16
   - u32
   - s32
   - u64
   - s64
   - mac
   - oid
   - ip4
   - ip6
   - ipaddr
   - objlist
   - vlanlist
   - aclfield
   - aclaction
   - u8list
   - s8list
   - u32list
   - s32list
   - qosmap
  """

  thrift_spec = (
    None, # 0
    (1, TType.BOOL, 'booldata', None, None, ), # 1
    (2, TType.STRING, 'chardata', None, None, ), # 2
    (3, TType.BYTE, 'u8', None, None, ), # 3
    (4, TType.BYTE, 's8', None, None, ), # 4
    (5, TType.I16, 'u16', None, None, ), # 5
    (6, TType.I16, 's16', None, None, ), # 6
    (7, TType.I32, 'u32', None, None, ), # 7
    (8, TType.I32, 's32', None, None, ), # 8
    (9, TType.I64, 'u64', None, None, ), # 9
    (10, TType.I64, 's64', None, None, ), # 10
    (11, TType.STRING, 'mac', None, None, ), # 11
    (12, TType.I64, 'oid', None, None, ), # 12
    (13, TType.STRING, 'ip4', None, None, ), # 13
    (14, TType.STRING, 'ip6', None, None, ), # 14
    (15, TType.STRUCT, 'ipaddr', (sai_thrift_ip_address_t, sai_thrift_ip_address_t.thrift_spec), None, ), # 15
    (16, TType.STRUCT, 'objlist', (sai_thrift_object_list_t, sai_thrift_object_list_t.thrift_spec), None, ), # 16
    (17, TType.STRUCT, 'vlanlist', (sai_thrift_vlan_list_t, sai_thrift_vlan_list_t.thrift_spec), None, ), # 17
    (18, TType.STRUCT, 'aclfield', (sai_thrift_acl_field_data_t, sai_thrift_acl_field_data_t.thrift_spec), None, ), # 18
    (19, TType.STRUCT, 'aclaction', (sai_thrift_acl_action_data_t, sai_thrift_acl_action_data_t.thrift_spec), None, ), # 19
    (20, TType.STRUCT, 'u8list', (sai_thrift_u8_list_t, sai_thrift_u8_list_t.thrift_spec), None, ), # 20
    (21, TType.STRUCT, 's8list', (sai_thrift_s8_list_t, sai_thrift_s8_list_t.thrift_spec), None, ), # 21
    (22, TType.STRUCT, 'u32list', (sai_thrift_u32_list_t, sai_thrift_u32_list_t.thrift_spec), None, ), # 22
    (23, TType.STRUCT, 's32list', (sai_thrift_s32_list_t, sai_thrift_s32_list_t.thrift_spec), None, ), # 23
    (24, TType.STRUCT, 'qosmap', (sai_thrift_qos_map_list_t, sai_thrift_qos_map_list_t.thrift_spec), None, ), # 24
  )

  def __init__(self, booldata=None, chardata=None, u8=None, s8=None, u16=None, s16=None, u32=None, s32=None, u64=None, s64=None, mac=None, oid=None, ip4=None, ip6=None, ipaddr=None, objlist=None, vlanlist=None, aclfield=None, aclaction=None, u8list=None, s8list=None, u32list=None, s32list=None, qosmap=None,):
    self.booldata = booldata
    self.chardata = chardata
    self.u8 = u8
    self.s8 = s8
    self.u16 = u16
    self.s16 = s16
    self.u32 = u32
    self.s32 = s32
    self.u64 = u64
    self.s64 = s64
    self.mac = mac
    self.oid = oid
    self.ip4 = ip4
    self.ip6 = ip6
    self.ipaddr = ipaddr
    self.objlist = objlist
    self.vlanlist = vlanlist
    self.aclfield = aclfield
    self.aclaction = aclaction
    self.u8list = u8list
    self.s8list = s8list
    self.u32list = u32list
    self.s32list = s32list
    self.qosmap = qosmap

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.BOOL:
          self.booldata = iprot.readBool();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.chardata = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.BYTE:
          self.u8 = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.BYTE:
          self.s8 = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.I16:
          self.u16 = iprot.readI16();
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.I16:
          self.s16 = iprot.readI16();
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.I32:
          self.u32 = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 8:
        if ftype == TType.I32:
          self.s32 = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 9:
        if ftype == TType.I64:
          self.u64 = iprot.readI64();
        else:
          iprot.skip(ftype)
      elif fid == 10:
        if ftype == TType.I64:
          self.s64 = iprot.readI64();
        else:
          iprot.skip(ftype)
      elif fid == 11:
        if ftype == TType.STRING:
          self.mac = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 12:
        if ftype == TType.I64:
          self.oid = iprot.readI64();
        else:
          iprot.skip(ftype)
      elif fid == 13:
        if ftype == TType.STRING:
          self.ip4 = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 14:
        if ftype == TType.STRING:
          self.ip6 = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 15:
        if ftype == TType.STRUCT:
          self.ipaddr = sai_thrift_ip_address_t()
          self.ipaddr.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 16:
        if ftype == TType.STRUCT:
          self.objlist = sai_thrift_object_list_t()
          self.objlist.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 17:
        if ftype == TType.STRUCT:
          self.vlanlist = sai_thrift_vlan_list_t()
          self.vlanlist.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 18:
        if ftype == TType.STRUCT:
          self.aclfield = sai_thrift_acl_field_data_t()
          self.aclfield.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 19:
        if ftype == TType.STRUCT:
          self.aclaction = sai_thrift_acl_action_data_t()
          self.aclaction.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 20:
        if ftype == TType.STRUCT:
          self.u8list = sai_thrift_u8_list_t()
          self.u8list.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 21:
        if ftype == TType.STRUCT:
          self.s8list = sai_thrift_s8_list_t()
          self.s8list.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 22:
        if ftype == TType.STRUCT:
          self.u32list = sai_thrift_u32_list_t()
          self.u32list.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 23:
        if ftype == TType.STRUCT:
          self.s32list = sai_thrift_s32_list_t()
          self.s32list.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 24:
        if ftype == TType.STRUCT:
          self.qosmap = sai_thrift_qos_map_list_t()
          self.qosmap.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_attribute_value_t')
    if self.booldata is not None:
      oprot.writeFieldBegin('booldata', TType.BOOL, 1)
      oprot.writeBool(self.booldata)
      oprot.writeFieldEnd()
    if self.chardata is not None:
      oprot.writeFieldBegin('chardata', TType.STRING, 2)
      oprot.writeString(self.chardata)
      oprot.writeFieldEnd()
    if self.u8 is not None:
      oprot.writeFieldBegin('u8', TType.BYTE, 3)
      oprot.writeByte(self.u8)
      oprot.writeFieldEnd()
    if self.s8 is not None:
      oprot.writeFieldBegin('s8', TType.BYTE, 4)
      oprot.writeByte(self.s8)
      oprot.writeFieldEnd()
    if self.u16 is not None:
      oprot.writeFieldBegin('u16', TType.I16, 5)
      oprot.writeI16(self.u16)
      oprot.writeFieldEnd()
    if self.s16 is not None:
      oprot.writeFieldBegin('s16', TType.I16, 6)
      oprot.writeI16(self.s16)
      oprot.writeFieldEnd()
    if self.u32 is not None:
      oprot.writeFieldBegin('u32', TType.I32, 7)
      oprot.writeI32(self.u32)
      oprot.writeFieldEnd()
    if self.s32 is not None:
      oprot.writeFieldBegin('s32', TType.I32, 8)
      oprot.writeI32(self.s32)
      oprot.writeFieldEnd()
    if self.u64 is not None:
      oprot.writeFieldBegin('u64', TType.I64, 9)
      oprot.writeI64(self.u64)
      oprot.writeFieldEnd()
    if self.s64 is not None:
      oprot.writeFieldBegin('s64', TType.I64, 10)
      oprot.writeI64(self.s64)
      oprot.writeFieldEnd()
    if self.mac is not None:
      oprot.writeFieldBegin('mac', TType.STRING, 11)
      oprot.writeString(self.mac)
      oprot.writeFieldEnd()
    if self.oid is not None:
      oprot.writeFieldBegin('oid', TType.I64, 12)
      oprot.writeI64(self.oid)
      oprot.writeFieldEnd()
    if self.ip4 is not None:
      oprot.writeFieldBegin('ip4', TType.STRING, 13)
      oprot.writeString(self.ip4)
      oprot.writeFieldEnd()
    if self.ip6 is not None:
      oprot.writeFieldBegin('ip6', TType.STRING, 14)
      oprot.writeString(self.ip6)
      oprot.writeFieldEnd()
    if self.ipaddr is not None:
      oprot.writeFieldBegin('ipaddr', TType.STRUCT, 15)
      self.ipaddr.write(oprot)
      oprot.writeFieldEnd()
    if self.objlist is not None:
      oprot.writeFieldBegin('objlist', TType.STRUCT, 16)
      self.objlist.write(oprot)
      oprot.writeFieldEnd()
    if self.vlanlist is not None:
      oprot.writeFieldBegin('vlanlist', TType.STRUCT, 17)
      self.vlanlist.write(oprot)
      oprot.writeFieldEnd()
    if self.aclfield is not None:
      oprot.writeFieldBegin('aclfield', TType.STRUCT, 18)
      self.aclfield.write(oprot)
      oprot.writeFieldEnd()
    if self.aclaction is not None:
      oprot.writeFieldBegin('aclaction', TType.STRUCT, 19)
      self.aclaction.write(oprot)
      oprot.writeFieldEnd()
    if self.u8list is not None:
      oprot.writeFieldBegin('u8list', TType.STRUCT, 20)
      self.u8list.write(oprot)
      oprot.writeFieldEnd()
    if self.s8list is not None:
      oprot.writeFieldBegin('s8list', TType.STRUCT, 21)
      self.s8list.write(oprot)
      oprot.writeFieldEnd()
    if self.u32list is not None:
      oprot.writeFieldBegin('u32list', TType.STRUCT, 22)
      self.u32list.write(oprot)
      oprot.writeFieldEnd()
    if self.s32list is not None:
      oprot.writeFieldBegin('s32list', TType.STRUCT, 23)
      self.s32list.write(oprot)
      oprot.writeFieldEnd()
    if self.qosmap is not None:
      oprot.writeFieldBegin('qosmap', TType.STRUCT, 24)
      self.qosmap.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.booldata)
    value = (value * 31) ^ hash(self.chardata)
    value = (value * 31) ^ hash(self.u8)
    value = (value * 31) ^ hash(self.s8)
    value = (value * 31) ^ hash(self.u16)
    value = (value * 31) ^ hash(self.s16)
    value = (value * 31) ^ hash(self.u32)
    value = (value * 31) ^ hash(self.s32)
    value = (value * 31) ^ hash(self.u64)
    value = (value * 31) ^ hash(self.s64)
    value = (value * 31) ^ hash(self.mac)
    value = (value * 31) ^ hash(self.oid)
    value = (value * 31) ^ hash(self.ip4)
    value = (value * 31) ^ hash(self.ip6)
    value = (value * 31) ^ hash(self.ipaddr)
    value = (value * 31) ^ hash(self.objlist)
    value = (value * 31) ^ hash(self.vlanlist)
    value = (value * 31) ^ hash(self.aclfield)
    value = (value * 31) ^ hash(self.aclaction)
    value = (value * 31) ^ hash(self.u8list)
    value = (value * 31) ^ hash(self.s8list)
    value = (value * 31) ^ hash(self.u32list)
    value = (value * 31) ^ hash(self.s32list)
    value = (value * 31) ^ hash(self.qosmap)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_attribute_t:
  """
  Attributes:
   - id
   - value
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'id', None, None, ), # 1
    (2, TType.STRUCT, 'value', (sai_thrift_attribute_value_t, sai_thrift_attribute_value_t.thrift_spec), None, ), # 2
  )

  def __init__(self, id=None, value=None,):
    self.id = id
    self.value = value

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.id = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRUCT:
          self.value = sai_thrift_attribute_value_t()
          self.value.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_attribute_t')
    if self.id is not None:
      oprot.writeFieldBegin('id', TType.I32, 1)
      oprot.writeI32(self.id)
      oprot.writeFieldEnd()
    if self.value is not None:
      oprot.writeFieldBegin('value', TType.STRUCT, 2)
      self.value.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.id)
    value = (value * 31) ^ hash(self.value)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_route_entry_t:
  """
  Attributes:
   - vr_id
   - destination
  """

  thrift_spec = (
    None, # 0
    (1, TType.I64, 'vr_id', None, None, ), # 1
    (2, TType.STRUCT, 'destination', (sai_thrift_ip_prefix_t, sai_thrift_ip_prefix_t.thrift_spec), None, ), # 2
  )

  def __init__(self, vr_id=None, destination=None,):
    self.vr_id = vr_id
    self.destination = destination

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I64:
          self.vr_id = iprot.readI64();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRUCT:
          self.destination = sai_thrift_ip_prefix_t()
          self.destination.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_route_entry_t')
    if self.vr_id is not None:
      oprot.writeFieldBegin('vr_id', TType.I64, 1)
      oprot.writeI64(self.vr_id)
      oprot.writeFieldEnd()
    if self.destination is not None:
      oprot.writeFieldBegin('destination', TType.STRUCT, 2)
      self.destination.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.vr_id)
    value = (value * 31) ^ hash(self.destination)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_neighbor_entry_t:
  """
  Attributes:
   - rif_id
   - ip_address
  """

  thrift_spec = (
    None, # 0
    (1, TType.I64, 'rif_id', None, None, ), # 1
    (2, TType.STRUCT, 'ip_address', (sai_thrift_ip_address_t, sai_thrift_ip_address_t.thrift_spec), None, ), # 2
  )

  def __init__(self, rif_id=None, ip_address=None,):
    self.rif_id = rif_id
    self.ip_address = ip_address

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I64:
          self.rif_id = iprot.readI64();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRUCT:
          self.ip_address = sai_thrift_ip_address_t()
          self.ip_address.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_neighbor_entry_t')
    if self.rif_id is not None:
      oprot.writeFieldBegin('rif_id', TType.I64, 1)
      oprot.writeI64(self.rif_id)
      oprot.writeFieldEnd()
    if self.ip_address is not None:
      oprot.writeFieldBegin('ip_address', TType.STRUCT, 2)
      self.ip_address.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.rif_id)
    value = (value * 31) ^ hash(self.ip_address)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_ipmc_entry_t:
  """
  Attributes:
   - vr_id
   - type
   - source
   - destination
  """

  thrift_spec = (
    None, # 0
    (1, TType.I64, 'vr_id', None, None, ), # 1
    (2, TType.BYTE, 'type', None, None, ), # 2
    (3, TType.STRUCT, 'source', (sai_thrift_ip_address_t, sai_thrift_ip_address_t.thrift_spec), None, ), # 3
    (4, TType.STRUCT, 'destination', (sai_thrift_ip_address_t, sai_thrift_ip_address_t.thrift_spec), None, ), # 4
  )

  def __init__(self, vr_id=None, type=None, source=None, destination=None,):
    self.vr_id = vr_id
    self.type = type
    self.source = source
    self.destination = destination

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I64:
          self.vr_id = iprot.readI64();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.BYTE:
          self.type = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRUCT:
          self.source = sai_thrift_ip_address_t()
          self.source.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.STRUCT:
          self.destination = sai_thrift_ip_address_t()
          self.destination.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_ipmc_entry_t')
    if self.vr_id is not None:
      oprot.writeFieldBegin('vr_id', TType.I64, 1)
      oprot.writeI64(self.vr_id)
      oprot.writeFieldEnd()
    if self.type is not None:
      oprot.writeFieldBegin('type', TType.BYTE, 2)
      oprot.writeByte(self.type)
      oprot.writeFieldEnd()
    if self.source is not None:
      oprot.writeFieldBegin('source', TType.STRUCT, 3)
      self.source.write(oprot)
      oprot.writeFieldEnd()
    if self.destination is not None:
      oprot.writeFieldBegin('destination', TType.STRUCT, 4)
      self.destination.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.vr_id)
    value = (value * 31) ^ hash(self.type)
    value = (value * 31) ^ hash(self.source)
    value = (value * 31) ^ hash(self.destination)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_l2mc_entry_t:
  """
  Attributes:
   - bv_id
   - type
   - source
   - destination
  """

  thrift_spec = (
    None, # 0
    (1, TType.I64, 'bv_id', None, None, ), # 1
    (2, TType.BYTE, 'type', None, None, ), # 2
    (3, TType.STRUCT, 'source', (sai_thrift_ip_address_t, sai_thrift_ip_address_t.thrift_spec), None, ), # 3
    (4, TType.STRUCT, 'destination', (sai_thrift_ip_address_t, sai_thrift_ip_address_t.thrift_spec), None, ), # 4
  )

  def __init__(self, bv_id=None, type=None, source=None, destination=None,):
    self.bv_id = bv_id
    self.type = type
    self.source = source
    self.destination = destination

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I64:
          self.bv_id = iprot.readI64();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.BYTE:
          self.type = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRUCT:
          self.source = sai_thrift_ip_address_t()
          self.source.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.STRUCT:
          self.destination = sai_thrift_ip_address_t()
          self.destination.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_l2mc_entry_t')
    if self.bv_id is not None:
      oprot.writeFieldBegin('bv_id', TType.I64, 1)
      oprot.writeI64(self.bv_id)
      oprot.writeFieldEnd()
    if self.type is not None:
      oprot.writeFieldBegin('type', TType.BYTE, 2)
      oprot.writeByte(self.type)
      oprot.writeFieldEnd()
    if self.source is not None:
      oprot.writeFieldBegin('source', TType.STRUCT, 3)
      self.source.write(oprot)
      oprot.writeFieldEnd()
    if self.destination is not None:
      oprot.writeFieldBegin('destination', TType.STRUCT, 4)
      self.destination.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.bv_id)
    value = (value * 31) ^ hash(self.type)
    value = (value * 31) ^ hash(self.source)
    value = (value * 31) ^ hash(self.destination)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_mcast_fdb_entry_t:
  """
  Attributes:
   - mac_address
   - bv_id
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'mac_address', None, None, ), # 1
    (2, TType.I64, 'bv_id', None, None, ), # 2
  )

  def __init__(self, mac_address=None, bv_id=None,):
    self.mac_address = mac_address
    self.bv_id = bv_id

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.mac_address = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I64:
          self.bv_id = iprot.readI64();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_mcast_fdb_entry_t')
    if self.mac_address is not None:
      oprot.writeFieldBegin('mac_address', TType.STRING, 1)
      oprot.writeString(self.mac_address)
      oprot.writeFieldEnd()
    if self.bv_id is not None:
      oprot.writeFieldBegin('bv_id', TType.I64, 2)
      oprot.writeI64(self.bv_id)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.mac_address)
    value = (value * 31) ^ hash(self.bv_id)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_inseg_entry_t:
  """
  Attributes:
   - label
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'label', None, None, ), # 1
  )

  def __init__(self, label=None,):
    self.label = label

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.label = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_inseg_entry_t')
    if self.label is not None:
      oprot.writeFieldBegin('label', TType.I32, 1)
      oprot.writeI32(self.label)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.label)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_attribute_list_t:
  """
  Attributes:
   - attr_list
   - attr_count
   - status
  """

  thrift_spec = (
    None, # 0
    (1, TType.LIST, 'attr_list', (TType.STRUCT,(sai_thrift_attribute_t, sai_thrift_attribute_t.thrift_spec)), None, ), # 1
    (2, TType.I32, 'attr_count', None, None, ), # 2
    (3, TType.I32, 'status', None, None, ), # 3
  )

  def __init__(self, attr_list=None, attr_count=None, status=None,):
    self.attr_list = attr_list
    self.attr_count = attr_count
    self.status = status

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.LIST:
          self.attr_list = []
          (_etype52, _size49) = iprot.readListBegin()
          for _i53 in xrange(_size49):
            _elem54 = sai_thrift_attribute_t()
            _elem54.read(iprot)
            self.attr_list.append(_elem54)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.attr_count = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I32:
          self.status = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_attribute_list_t')
    if self.attr_list is not None:
      oprot.writeFieldBegin('attr_list', TType.LIST, 1)
      oprot.writeListBegin(TType.STRUCT, len(self.attr_list))
      for iter55 in self.attr_list:
        iter55.write(oprot)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.attr_count is not None:
      oprot.writeFieldBegin('attr_count', TType.I32, 2)
      oprot.writeI32(self.attr_count)
      oprot.writeFieldEnd()
    if self.status is not None:
      oprot.writeFieldBegin('status', TType.I32, 3)
      oprot.writeI32(self.status)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.attr_list)
    value = (value * 31) ^ hash(self.attr_count)
    value = (value * 31) ^ hash(self.status)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_result_data_t:
  """
  Attributes:
   - objlist
   - oid
   - u16
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRUCT, 'objlist', (sai_thrift_object_list_t, sai_thrift_object_list_t.thrift_spec), None, ), # 1
    (2, TType.I64, 'oid', None, None, ), # 2
    (3, TType.I16, 'u16', None, None, ), # 3
  )

  def __init__(self, objlist=None, oid=None, u16=None,):
    self.objlist = objlist
    self.oid = oid
    self.u16 = u16

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRUCT:
          self.objlist = sai_thrift_object_list_t()
          self.objlist.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I64:
          self.oid = iprot.readI64();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I16:
          self.u16 = iprot.readI16();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_result_data_t')
    if self.objlist is not None:
      oprot.writeFieldBegin('objlist', TType.STRUCT, 1)
      self.objlist.write(oprot)
      oprot.writeFieldEnd()
    if self.oid is not None:
      oprot.writeFieldBegin('oid', TType.I64, 2)
      oprot.writeI64(self.oid)
      oprot.writeFieldEnd()
    if self.u16 is not None:
      oprot.writeFieldBegin('u16', TType.I16, 3)
      oprot.writeI16(self.u16)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.objlist)
    value = (value * 31) ^ hash(self.oid)
    value = (value * 31) ^ hash(self.u16)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class sai_thrift_result_t:
  """
  Attributes:
   - data
   - status
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRUCT, 'data', (sai_thrift_result_data_t, sai_thrift_result_data_t.thrift_spec), None, ), # 1
    (2, TType.I32, 'status', None, None, ), # 2
  )

  def __init__(self, data=None, status=None,):
    self.data = data
    self.status = status

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRUCT:
          self.data = sai_thrift_result_data_t()
          self.data.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.status = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('sai_thrift_result_t')
    if self.data is not None:
      oprot.writeFieldBegin('data', TType.STRUCT, 1)
      self.data.write(oprot)
      oprot.writeFieldEnd()
    if self.status is not None:
      oprot.writeFieldBegin('status', TType.I32, 2)
      oprot.writeI32(self.status)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.data)
    value = (value * 31) ^ hash(self.status)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)
